root: true
env:
    browser: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:import/recommended
    - plugin:import/typescript
plugins:
    - 'typescript-eslint'
settings:
    import/resolver:
        typescript: true
        node:
            extensions:
                - '.js'
                - '.jsx'
                - '.ts'
                - '.tsx'

parser: '@typescript-eslint/parser'
parserOptions:
    project: 'tsconfig.json'
