root: true
env:
    browser: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:@typescript-eslint/recommended
    - plugin:import/recommended
    - plugin:import/typescript
settings:
    import/resolver:
        typescript: true
parser: '@typescript-eslint/parser'
parserOptions:
    project: 'tsconfig.json'
